/*
 *
 *  *  Copyright (c) 2020  Stefan Spiska (Vitasystems GmbH) and Hannover Medical School
 *  *  This file is part of Project EHRbase
 *  *
 *  *  Licensed under the Apache License, Version 2.0 (the "License");
 *  *  you may not use this file except in compliance with the License.
 *  *  You may obtain a copy of the License at
 *  *
 *  *  http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  *  Unless required by applicable law or agreed to in writing, software
 *  *  distributed under the License is distributed on an "AS IS" BASIS,
 *  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  *  See the License for the specific language governing permissions and
 *  *  limitations under the License.
 *
 */

package org.ehrbase.webtemplate.parser;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.apache.commons.io.IOUtils;
import org.apache.commons.lang3.tuple.ImmutablePair;
import org.apache.xmlbeans.XmlException;
import org.assertj.core.groups.Tuple;
import org.ehrbase.test_data.operationaltemplate.OperationalTemplateTestData;
import org.ehrbase.test_data.webtemplate.WebTemplateTestData;
import org.ehrbase.webtemplate.filter.Filter;
import org.ehrbase.webtemplate.model.WebTemplate;
import org.ehrbase.webtemplate.model.WebTemplateInput;
import org.ehrbase.webtemplate.model.WebTemplateInputValue;
import org.ehrbase.webtemplate.model.WebTemplateNode;
import org.junit.Test;
import org.openehr.schemas.v1.OPERATIONALTEMPLATE;
import org.openehr.schemas.v1.TemplateDocument;

public class OPTParserTest {

  @Test
  public void parseCoronaAnamnese() throws IOException, XmlException {
    OPERATIONALTEMPLATE template =
        TemplateDocument.Factory.parse(OperationalTemplateTestData.CORONA_ANAMNESE.getStream())
            .getTemplate();

    OPTParser cut = new OPTParser(template);
    WebTemplate actual = cut.parse();
    actual = new Filter().filter(actual);
    assertThat(actual).isNotNull();

    ObjectMapper objectMapper = new ObjectMapper();
    WebTemplate expected =
        objectMapper.readValue(
            IOUtils.toString(WebTemplateTestData.CORONA.getStream(), StandardCharsets.UTF_8),
            WebTemplate.class);

    List<String> errors = compareWebTemplate(actual, expected);

    // Nodes wich are generated by the parser but are not in the example

    assertThat(errors)
        .filteredOn(s -> s.contains("Extra Node"))
        .containsExactlyInAnyOrder(
            "Extra Node id=end_time aql=/context/end_time",
            "Extra Node id=health_care_facility aql=/context/health_care_facility",
            "Extra Node id=aufenthalt_in_den_letzten_14_tage_in_einem_der_risikogebiete_für_coronainfektion_oder_kontakt_zu_menschen_die_dort_waren aql=/content[openEHR-EHR-SECTION.adhoc.v1 and name/value='Risikogebiet']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0111 and name/value='Aufenthalt in den letzten 14 Tage in einem der Risikogebiete für Coronainfektion oder Kontakt zu Menschen, die dort waren']/value");

    // Nodes wich are in the example but are not generated by the parser
    assertThat(errors)
        .filteredOn(s -> s.contains("Missing Node"))
        .containsExactlyInAnyOrder(
            "Missing Node id=action_archetype_id aql=/content[openEHR-EHR-SECTION.adhoc.v1 and name/value='Allgemeine Angaben']/items[openEHR-EHR-INSTRUCTION.service_request.v1]/activities[at0001]/action_archetype_id",
            "Missing Node id=aufenthalt_in_den_letzten_14_tage_in_einem_der_risikogebiete_für_coronainfektion_oder_kontakt_zu_menschen_die_dort_waren aql=/content[openEHR-EHR-SECTION.adhoc.v1 and name/value='Risikogebiet']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0111 and name/value='Aufenthalt in den letzten 14 Tage in einem der Risikogebiete für Coronainfektion oder Kontakt zu Menschen']/value");
  }

  @Test
  public void parseAltEvents() throws IOException, XmlException {
    OPERATIONALTEMPLATE template =
        TemplateDocument.Factory.parse(OperationalTemplateTestData.ALT_EVENTS.getStream())
            .getTemplate();

    OPTParser cut = new OPTParser(template);
    WebTemplate actual = cut.parse();
    actual = new Filter().filter(actual);
    assertThat(actual).isNotNull();

    ObjectMapper objectMapper = new ObjectMapper();
    WebTemplate expected =
        objectMapper.readValue(
            IOUtils.toString(
                WebTemplateTestData.ALTERNATIVE_EVENTS.getStream(), StandardCharsets.UTF_8),
            WebTemplate.class);

    List<String> errors = compareWebTemplate(actual, expected);

    // Nodes wich are generated by the parser but are not in the example
    assertThat(errors)
        .filteredOn(s -> s.contains("Extra Node"))
        .containsExactlyInAnyOrder(
            "Extra Node id=end_time aql=/context/end_time",
            "Extra Node id=health_care_facility aql=/context/health_care_facility");

    // Nodes wich are in the example but are not generated by the parser
    assertThat(errors).filteredOn(s -> s.contains("Missing Node")).containsExactlyInAnyOrder();
  }

  @Test
  public void parseMultiOccurrence() throws IOException, XmlException {
    OPERATIONALTEMPLATE template =
        TemplateDocument.Factory.parse(OperationalTemplateTestData.MULTI_OCCURRENCE.getStream())
            .getTemplate();

    OPTParser cut = new OPTParser(template);
    WebTemplate actual = cut.parse();
    actual = new Filter().filter(actual);
    assertThat(actual).isNotNull();

    ObjectMapper objectMapper = new ObjectMapper();
    WebTemplate expected =
        objectMapper.readValue(
            IOUtils.toString(
                WebTemplateTestData.MULTI_OCCURRENCE.getStream(), StandardCharsets.UTF_8),
            WebTemplate.class);

    List<String> errors = compareWebTemplate(actual, expected);

    // Nodes wich are generated by the parser but are not in the example
    assertThat(errors)
        .filteredOn(s -> s.contains("Extra Node"))
        .containsExactlyInAnyOrder(
            "Extra Node id=end_time aql=/context/end_time",
            "Extra Node id=health_care_facility aql=/context/health_care_facility");

    // Nodes wich are in the example but are not generated by the parser
    assertThat(errors).filteredOn(s -> s.contains("Missing Node")).containsExactlyInAnyOrder();
  }

  @Test
  public void parseAllTypes() throws IOException, XmlException {
    OPERATIONALTEMPLATE template =
        TemplateDocument.Factory.parse(OperationalTemplateTestData.ALL_TYPES.getStream())
            .getTemplate();

    OPTParser cut = new OPTParser(template);
    WebTemplate actual = cut.parse();
    actual = new Filter().filter(actual);
    assertThat(actual).isNotNull();

    ObjectMapper objectMapper = new ObjectMapper();
    WebTemplate expected =
        objectMapper.readValue(
            IOUtils.toString(WebTemplateTestData.ALL_TYPES.getStream(), StandardCharsets.UTF_8),
            WebTemplate.class);

    List<WebTemplateNode> dvOrdinalList =
        actual.getTree().findMatching(n -> n.getRmType().equals("DV_ORDINAL"));
    assertThat(dvOrdinalList).size().isEqualTo(1);
    assertThat(dvOrdinalList.get(0).getInputs())
        .flatExtracting(WebTemplateInput::getList)
        .extracting(
            WebTemplateInputValue::getLabel,
            WebTemplateInputValue::getValue,
            WebTemplateInputValue::getOrdinal)
        .containsExactlyInAnyOrder(
            new Tuple("ord1", "at0014", 0),
            new Tuple("ord1", "at0015", 1),
            new Tuple("ord3", "at0016", 2));

    List<WebTemplateNode> dvQuantityList =
        actual.getTree().findMatching(n -> n.getRmType().equals("DV_QUANTITY"));
    assertThat(dvQuantityList)
        .flatExtracting(WebTemplateNode::getInputs)
        .flatExtracting(WebTemplateInput::getList)
        .extracting(WebTemplateInputValue::getLabel, WebTemplateInputValue::getValue)
        .containsExactlyInAnyOrder(
            new Tuple("mg", "mg"),
            new Tuple("kg", "kg"),
            new Tuple("mm[H20]", "mm[H20]"),
            new Tuple("mm[Hg]", "mm[Hg]"));
    List<WebTemplateNode> dvCodedTextList =
        actual.getTree().findMatching(n -> n.getRmType().equals("DV_CODED_TEXT"));
    assertThat(dvCodedTextList)
        .flatExtracting(WebTemplateNode::getInputs)
        .extracting(
            WebTemplateInput::getTerminology,
            i ->
                i.getList().stream()
                    .map(v -> v.getValue() + ":" + v.getLabel())
                    .collect(Collectors.joining(";")))
        .containsExactlyInAnyOrder(
            new Tuple("local", "at0006:value1;at0007:value2;at0008:value3"),
            new Tuple("local", ""),
            new Tuple("SNOMED-CT", ""),
            new Tuple("openehr", "at0003:Planned;at0004:Active;at0005:Completed"),
            new Tuple("openehr", "526:planned;245:active;532:completed"));

    List<String> errors = compareWebTemplate(actual, expected);

    // Nodes wich are generated by the parser but are not in the example
    assertThat(errors)
        .filteredOn(s -> s.contains("Extra Node"))
        .containsExactlyInAnyOrder(
            "Extra Node id=end_time aql=/context/end_time",
            "Extra Node id=health_care_facility aql=/context/health_care_facility");

    // Nodes wich are in the example but are not generated by the parser
    assertThat(errors)
        .filteredOn(s -> s.contains("Missing Node"))
        .containsExactlyInAnyOrder(
            "Missing Node id=action_archetype_id aql=/content[openEHR-EHR-SECTION.test_all_types.v1]/items[at0001]/items[at0002]/items[openEHR-EHR-INSTRUCTION.test_all_types.v1]/activities[at0001]/action_archetype_id");
  }

  public List<String> compareWebTemplate(WebTemplate actual, WebTemplate expected) {
    List<String> errors = new ArrayList<>();
    errors.addAll(compareNode(actual.getTree(), expected.getTree()));
    return errors;
  }

  public List<String> compareNodes(List<WebTemplateNode> actual, List<WebTemplateNode> expected) {
    List<String> errors = new ArrayList<>();
    Map<ImmutablePair<String, String>, WebTemplateNode> actualMap =
        actual.stream()
            .collect(
                Collectors.toMap(
                    n -> new ImmutablePair<>(n.getAqlPath(true), n.getId()), Function.identity()));
    Map<ImmutablePair<String, String>, WebTemplateNode> expectedMap =
        expected.stream()
            .collect(
                Collectors.toMap(
                    n -> new ImmutablePair<>(n.getAqlPath(true), n.getId()), Function.identity()));

    for (ImmutablePair<String, String> pair : actualMap.keySet()) {
      if (expectedMap.containsKey(pair)) {
        errors.addAll(compareNode(actualMap.get(pair), expectedMap.get(pair)));
      } else {
        errors.add(String.format("Extra Node id=%s aql=%s", pair.getRight(), pair.getLeft()));
      }
    }
    for (ImmutablePair<String, String> pair : expectedMap.keySet()) {
      if (!actualMap.containsKey(pair)) {
        errors.add(String.format("Missing Node id=%s aql=%s", pair.getRight(), pair.getLeft()));
      }
    }
    return errors;
  }

  public List<String> compareNode(WebTemplateNode actual, WebTemplateNode expected) {

    List<String> errors = new ArrayList<>();
    errors.addAll(compareNodes(actual.getChildren(), expected.getChildren()));
    return errors;
  }
}
