package org.ehrbase.client.classgenerator.examples.virologischerbefundcomposition.definition;

public interface LaboranalytResultatAnalytResultatChoiceOrgEhrbaseEhrEncodeWrappersSnakecase40f33492 {
}
