name: Bug Report
description: Report a bug encountered when working with openEHR_SDK
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Before reporting an issue
      description: Please search to see if the issue is already reported, and try to reproduce the issue on the latest release.
      options:
        - label: I have searched existing issues
          required: true
        - label: I have reproduced the issue with the latest release
          required: true
  - type: textarea
    attributes:
      label: Environment information
      description: |
        To help reproducing your problem it is mandatory to give some information on the environment. 
        
        If the bug was encountered while working with EHRbase please provide the EHRbase version as well.
        You can get an aggregate environment of EHRbase by starting EHRbase and performing a GET request on `%ehrbaseBaseUri%/ehrbase/rest/status`
      placeholder: |
        - openEHR_SDK version:
        - Archie version:
        - PostgreSQL version:
        - Java Runtime version:
        - Operating System version:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe the steps that you have taken until the unexpected behavior occurred. Please try to add as many details as possible, and include data and templates as attachments.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe the expected output / behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual result
      description: Describe the wrong output / behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Further information
      description: Add additional information, if needed.
    validations:
      required: false