name: Enhancement Request
description: Enhancement request for a new / extended functionality of the openEHR_SDK
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Background
      description: Describe the context and intention for this enhancement, such as the benefits and impacts on the user.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Enhancement
      description: Provide specific preconditions, steps, requirements or expectations on theproposed enhancement.
    validations:
      required: true
  - type: input
    attributes:
      label: Discussion
      description: |
        If there has been a discussion around the enhancement, provide a link to the discussion.
        Please also check for ongoing discussions on the [openEHR discourse](https://discourse.openehr.org/).
  - type: textarea
    attributes:
      label: Further information
      description: Add additional information, if needed.
    validations:
      required: false