/*
 * Copyright (c) 2019 vitasystems GmbH and Hannover Medical School.
 *
 * This file is part of project openEHR_SDK
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.openehr.sdk.validation.terminology;

import static com.nedap.archie.rmutil.InvariantUtil.ENGLISH;
import static org.assertj.core.api.Assertions.*;
import static org.ehrbase.openehr.sdk.terminology.TerminologyProvider.OPENEHR;

import com.nedap.archie.rm.datatypes.CodePhrase;
import com.nedap.archie.rm.datavalues.DvCodedText;
import com.nedap.archie.rm.support.identification.TerminologyId;
import org.ehrbase.openehr.sdk.validation.terminology.check.CodePhraseCheck;
import org.ehrbase.openehr.sdk.validation.terminology.check.DvCodedTextCheck;
import org.junit.jupiter.api.Test;

class TerminologyCheckTest {

    @Test
    void testSimpleValidation() {
        DvCodedText category = new DvCodedText("event", new CodePhrase(new TerminologyId(OPENEHR), "433"));
        DvCodedTextCheck.validate("category", category, ENGLISH);
    }

    @Test
    void testSimpleValidationWrongCode() {
        DvCodedText category = new DvCodedText("event", new CodePhrase(new TerminologyId(OPENEHR), "999"));
        assertThatThrownBy(() -> {
                    DvCodedTextCheck.validate("category", category, ENGLISH);
                })
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void testSimpleValidationWrongValue() {
        DvCodedText category =
                new DvCodedText("not quite sure what to put here", new CodePhrase(new TerminologyId(OPENEHR), "433"));
        assertThatThrownBy(() -> {
                    DvCodedTextCheck.validate("category", category, ENGLISH);
                })
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void testSimpleValidationLanguageWrong() {
        CodePhrase codePhrase = new CodePhrase(new TerminologyId("ISO_3166-1"), "ZZ");
        assertThatThrownBy(() -> {
                    CodePhraseCheck.validate("territory", codePhrase, ENGLISH);
                })
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void testSimpleValidationSymbol() {
        DvCodedText symbol = new DvCodedText(
                "autogenerated (node doesn't have a constraint)",
                new CodePhrase(new TerminologyId("http://hl7.org/fhir/contact-point-use"), "BCDWXMEORP"));
        DvCodedTextCheck.validate("symbol", symbol, ENGLISH);
    }
}
