package org.ehrbase.client.classgenerator.examples.coronaanamnesecomposition.definition;

public interface KontaktOrgEhrbaseEhrEncodeWrappersSnakecase732c9b5cExposureScreeningQuestionnaireEnChoice {
}
