package org.ehrbase.client.classgenerator.examples.patientenaufenthaltcomposition.definition;

public interface PatientenaufenthaltOrgEhrbaseEhrEncodeWrappersSnakecase6ab72419FallidentifikationChoice {
}
