name: "Codestyle"

# we have multiple workflows - this helps to distinguish for them
run-name: "${{ github.event.pull_request.title || github.head_ref }} - Codestyle"

on:
  push:
    branches: [ develop, release/* ]
  workflow_dispatch:
  pull_request:
    branches: [ develop ]

#
# Style-check it's a dedicated workflow. This allows us to open a PR, run all tests and fix styling issue later ;).
#
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Spotless
        run: mvn spotless:check
